import { Mtf } from '../types';
import { Panel } from '../motion/primitives';
import { IconTrend } from '../motion/Icons';

/* ============================================================================
   MTF trend gauge — the indicator's multi-timeframe dashboard.
   EMA11 vs EMA34 on every configured timeframe (5m / 15m / 30m by default):
   EMA34 < EMA11 ⇒ Bullish. The needle angle follows the bullish share.
   ========================================================================== */

export function MtfGauge({ mtf }: { mtf: Mtf | null }) {
  const frames = mtf?.timeframes ?? [];
  const bullCount = mtf?.bullCount ?? frames.filter((t) => t.bull).length;
  const total = frames.length;
  const share = total ? bullCount / total : 0.5;
  // -90° (all bearish) … +90° (all bullish)
  const angle = -90 + share * 180;
  const verdict = mtf?.overall && mtf.overall !== '—' ? mtf.overall : total ? (share >= 0.5 ? 'BULLISH' : 'BEARISH') : '—';
  const bull = /bull/i.test(verdict);
  const R = 78;
  const CIRC = Math.PI * R; // length of the half circle (r × π)

  return (
    <div className="gauge">
      <svg className="gauge-svg" viewBox="0 0 200 118" role="img" aria-label={`Multi-timeframe trend ${verdict}`}>
        <defs>
          <linearGradient id="mtf-grad" x1="0" y1="0" x2="1" y2="0">
            <stop offset="0%" stopColor="#ff6b8b" />
            <stop offset="50%" stopColor="#ffc857" />
            <stop offset="100%" stopColor="#34f0b2" />
          </linearGradient>
        </defs>
        <path className="gauge-track" d={`M ${100 - R} 100 A ${R} ${R} 0 0 1 ${100 + R} 100`} />
        <path
          className="gauge-fill"
          stroke="url(#mtf-grad)"
          strokeDasharray={CIRC}
          strokeDashoffset={CIRC * (1 - share)}
          d={`M ${100 - R} 100 A ${R} ${R} 0 0 1 ${100 + R} 100`}
        />
        <g className="gauge-needle" style={{ transform: `rotate(${angle}deg)` }}>
          <line x1="100" y1="100" x2="100" y2="34" stroke="rgba(255,255,255,.75)" strokeWidth="2.5" strokeLinecap="round" />
          <circle cx="100" cy="100" r="5.5" fill="#0b1220" stroke="rgba(255,255,255,.7)" strokeWidth="2" />
        </g>
      </svg>
      <div className="gauge-center">
        <span className={`gauge-verdict ${bull ? 'bull' : 'bear'}`}>{verdict}</span>
        <span className="gauge-sub">
          {total ? `${bullCount}/${total} timeframes bullish` : 'warming up'}
        </span>
      </div>
      <div className="tf-chips">
        {frames.length === 0 && <span className="tf-chip">no multi-timeframe data yet</span>}
        {frames.map((f) => (
          <span key={f.tf} className={`tf-chip ${f.bull ? 'bull' : 'bear'}`}>
            <span className="tf-arrow">{f.bull ? '▲' : '▼'}</span>
            {f.tf}
          </span>
        ))}
      </div>
    </div>
  );
}

export function MtfPanel({ mtf, symbol }: { mtf: Mtf | null; symbol?: string }) {
  const atr = mtf?.atr ?? 0;
  return (
    <Panel
      title="MTF Trend"
      sub={`${symbol ?? mtf?.symbol ?? 'BTCUSDT'} · context only, not an entry gate`}
      icon={<IconTrend />}
      meta={<span className={`chip ${/bull/i.test(mtf?.overall ?? '') ? 'green' : 'red'}`}>{mtf?.overall ?? '—'}</span>}
    >
      <MtfGauge mtf={mtf} />
      <div className="hint mt" style={{ textAlign: 'center' }}>
        Ribbon {mtf?.ribbonBull ? 'bullish' : 'bearish'} · ATR(14) {atr ? atr.toFixed(4) : '—'} — the engine only
        entries are not generated by EMA signals. This gauge is shown only as broader market context; live entries require the 5m sweep → POC retest setup.
      </div>
    </Panel>
  );
}

export default MtfPanel;
