#!/usr/bin/env python3
"""Generate the indicator reference vectors used by server/scripts/smoke.js.

The generators below are an INDEPENDENT implementation (plain Python, no shared
code with the TypeScript port) of

    * EMA seeded with the SMA of the first `length` values  (Pine ta.ema)
    * Wilder ATR: RMA of the true range                    (Pine ta.atr)

so the smoke test is a real cross-check of the TypeScript maths rather than a
self-comparison.

Usage:  python3 server/scripts/gen-reference.py
Writes: server/scripts/fixtures/indicator-reference.json
"""
import json
import math
import os
from decimal import Decimal

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixtures", "indicator-reference.json")


def series(n: int = 240) -> list[float]:
    """Deterministic pseudo-market closes (seeded LCG + drift + cycle)."""
    state = 123456789
    out = []
    price = 100.0
    for i in range(n):
        state = (1103515245 * state + 12345) % (2**31)
        rnd = state / 2**31
        drift = 0.08 if i < n / 2 else -0.05
        price = price + drift + (rnd - 0.5) * 1.6 + math.sin(i / 9.0) * 0.35
        out.append(round(price, 8))
    return out


def candles(closes: list[float]) -> list[dict]:
    out = []
    for i, c in enumerate(closes):
        o = closes[i - 1] if i else c
        h = max(o, c) + 0.4 + (i % 5) * 0.07
        l = min(o, c) - 0.35 - (i % 3) * 0.09
        out.append({"open": o, "high": round(h, 8), "low": round(l, 8), "close": c, "volume": 100.0 + i})
    return out


def ema(values: list[float], length: int) -> list[float | None]:
    out: list[float | None] = [None] * len(values)
    if len(values) < length or length <= 0:
        return out
    alpha = 2.0 / (length + 1.0)
    prev = sum(values[:length]) / length
    out[length - 1] = prev
    for i in range(length, len(values)):
        prev = values[i] * alpha + prev * (1.0 - alpha)
        out[i] = prev
    return out


def atr(bars: list[dict], length: int) -> list[float | None]:
    n = len(bars)
    tr = [None] * n
    for i, b in enumerate(bars):
        if i == 0:
            tr[i] = b["high"] - b["low"]
        else:
            pc = bars[i - 1]["close"]
            tr[i] = max(b["high"] - b["low"], abs(b["high"] - pc), abs(b["low"] - pc))
    out: list[float | None] = [None] * n
    if n < length or length <= 0:
        return out
    prev = sum(tr[:length]) / length
    out[length - 1] = prev
    for i in range(length, n):
        prev = (prev * (length - 1) + tr[i]) / length
        out[i] = prev
    return out


def main() -> None:
    closes = series()
    bars = candles(closes)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    data = {
        "_note": "generated by gen-reference.py — independent Python implementation of Pine ta.ema / ta.atr",
        "closes": [Decimal(str(c)).__float__() for c in closes],
        "candles": bars,
        "indices": [10, 34, 50, 99, 150, 199, 239],
        "ema5": ema(closes, 5),
        "ema11": ema(closes, 11),
        "ema34": ema(closes, 34),
        "atr14": atr(bars, 14),
    }
    with open(OUT, "w") as fh:
        json.dump(data, fh)
        fh.write("\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
